### ISSUE TITLE
12:00 pm gets switched to 0:00 in 24 hour time

### ISSUE THREAD

**Issue by ReviewEdge** [ReviewEdge/ClassMaster#34]
"COMP 141 A, COMP PROGRAMMING I, [Monday 0:00 - 0:50, Wednesday 0:00 - 0:50, Friday 0:00 - 0:50], Brian Dellinger"

Issue is in Class.

**Comment by Jaxaar** [comment]
Fixed, Added if to 12 to 24hr method, so that 12pm was read as 12 instead of 12+12. 12am/pm is just weird
